[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = []

# Helpful security & perf headers (+ CORS only for our API host)
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Cache-Control = "public, max-age=600"
    Content-Security-Policy = "default-src 'self'; img-src 'self' data: blob: https://*; connect-src 'self' https://api.runware.ai; script-src 'self'; style-src 'self' 'unsafe-inline'; font-src https://fonts.gstatic.com; frame-ancestors 'self';"

# (Optional) redirect old paths to functions if you used them before
# [[redirects]]
#   from = "/generate"
#   to   = "/.netlify/functions/generate"
#   status = 200
